### ISSUE TITLE
Mint is not no_std

### ISSUE THREAD

**Issue by TheZoq2** [eupn/bno055#4]
Hi, thanks for putting in the effort to making this lib!

It looks like you added `mint` as a dependency in 0.3.0, but unfortunately, it doesn't seem to compile without the standard library and as far as I can tell, there is no feature to enable/disable to fix that.

Am I missing something obvious here?

**Comment by eupn** [comment]
Hey, thanks, I'll look into that! You can use the previous version that depends on `nalgebra` for now.

**Comment by eupn** [comment]
I've made a PR https://github.com/kvark/mint/pull/47 that will make `mint` a `no_std` library. Until it's being merged, please stick to the previous version of the crate.

**Comment by eupn** [comment]
PR is merged; I'll publish a new version of the crate as soon as `mint` will publish their's.

**Comment by eupn** [comment]
Version is bumped https://crates.io/crates/mint/0.5.4. Updating the `bno055` crate.

**Comment by eupn** [comment]
@TheZoq2 the crate should be able to build now after doing `cargo update`.

**Comment by TheZoq2** [comment]
Nice, thanks for the very quick fix!
